TRUNCATE TABLE favorites RESTART IDENTITY CASCADE;
TRUNCATE TABLE bookboxes RESTART IDENTITY CASCADE;
TRUNCATE TABLE tokens RESTART IDENTITY CASCADE;
TRUNCATE TABLE images RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE roles RESTART IDENTITY CASCADE;
